Support linux/arm64 using Dup3() instead of Dup2()
Dup3() will be used for linux on arm64 since Dup2() is unavailable.
The rest linux arches will still use Dup2().

Otherwise linux/arm64 building fails with:
src/github.com/linkedin/Burrow/core/open_out_log_unix.go:20:9: undefined: syscall.Dup2

Example of error from debian package auto-building:
https://buildd.debian.org/status/fetch.php?pkg=burrow&arch=arm64&ver=1.1.0-1&stamp=1528200955&raw=0